name: build
on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build:

    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      max-parallel: 4
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.11']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install gsl
          conda install ffmpeg
          pip install numpy pytest

      - name: Install pipenv
        shell: bash -l {0}
        run: |
          pip install .

      - name: Run test suite
        shell: bash -l {0}
        run: |
          python binaryBHexp.py --q 1.5 --chiA 0.6 0.4 0.1 --chiB 0.3 0.4 0.2 --omega_ref 1.8e-2 --auto_rotate_camera --save_file test.mp4
